dataset:
  input_dim: 3
  single: False
  stats: dafa_ls
  mask_mode: none
  pixel_set: 1024
model:
  name: backboneltae
  backbone: pse
  frozen: False
  in_channels: 128
training:
  criterion: bce
  weight: False
  n_epochs: 200
  batch_size: 8
  num_workers: 8
  optimizer:
    lr: 0.0001
    weight_decay: 0.01
  scheduler:
    warmup: 100
    gamma: 0.1
    num_iter_per_step: [10000, 20000]
    min_lr: 0.00001