dataset:
  width: 128
  height: 128
  input_dim: 3
  single: False
  stats: dafa_ls
  semantic: False
  mask_mode: multiply
  pixel_set: None
model:
  name: tsvit
  img_res: 128
  max_seq_len: 96
  num_channels: 3
  num_classes: 2
  dropout: 0.
  patch_size: 4
  dim: 32
  temporal_depth: 4
  spatial_depth: 4
  heads: 4
  pool: cls
  dim_head: 32
  emb_dropout: 0.
  scale_dim: 4
training:
  criterion: bce
  ignore_index: 0
  weight: False
  n_epochs: 100
  batch_size: 4
  num_workers: 8
  optimizer:
    lr: 0.0001
    weight_decay: 0.01
  scheduler:
    warmup: 100
    gamma: 0.1
    num_iter_per_step: [14000, 20000]
    min_lr: 0.00001