dataset:
  width: 224
  height: 224
  input_dim: 3
  single: False
  stats: imagenet
  mask_mode: multiply
  pixel_set: None
model:
  name: backboneltae
  backbone: vit_b_16
  frozen: True
  pretrained: True
  in_channels: 768
training:
  criterion: bce
  weight: False
  n_epochs: 200
  batch_size: 8
  num_workers: 8
  optimizer:
    lr: 0.0001
    weight_decay: 0.01
  scheduler:
    warmup: 100
    gamma: 0.1
    num_iter_per_step: [10000, 20000]
    min_lr: 0.00001